name: admin-service
services:
  admin-service:
    image: $CI_REGISTRY_IMAGE:latest
    restart: unless-stopped
    environment:
      - ENV=production
    networks:
      - nginx-network
networks:
  nginx-network:
    external: true
